name: pnpm-build
inputs:
  os:
    type: string
    required: false
    default: ubuntu-latest
  node-version:
    type: string
    required: false
    default: '20'
run:
  using: composite
  steps:
    - uses: actions/checkout@v6
    - uses: pnpm/action-setup@v4
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
    - name: Install Dependencies
      run: pnpm install
