name: typescript
on:
  push:
    branches:
      - $default-branch
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    uses: unional/.github/.github/workflows/typescript-build@main
  test:
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node-version: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - name: setup yarn-cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: cache yarn global cache
        if: runner.os != 'macos-latest'
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - run: yarn test --maxWorkers=2
  release:
    name: release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - build
      - test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup yarn-cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: cache yarn global cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: download cjs folder
        uses: actions/download-artifact@v2
        with:
          name: cjs
      - name: download esm folder
        uses: actions/download-artifact@v2
        with:
          name: esm
      - name: cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
