name: "Setup Playwright"
description: "Install Playwright browsers and dependencies with caching"
inputs:
  browsers:
    description: "Space-separated list of browsers to install (e.g., 'chromium', 'chromium webkit')"
    required: false
    default: "chromium"
  package-manager:
    description: "Package manager to use (pnpm, npm, yarn, bun, deno)"
    required: false
    default: "pnpm"
runs:
  using: "composite"
  steps:
    - name: Get Playwright version
      id: playwright-version
      shell: bash
      run: |
        # Extract Playwright version based on package manager
        case "${{ inputs.package-manager }}" in
          pnpm)
            VERSION=$(pnpm exec playwright --version | grep -oE '[0-9]+(\.[0-9]+)+')
            ;;
          npm)
            VERSION=$(npm exec playwright -- --version | grep -oE '[0-9]+(\.[0-9]+)+')
            ;;
          yarn)
            VERSION=$(yarn exec playwright --version | grep -oE '[0-9]+(\.[0-9]+)+')
            ;;
          bun)
            VERSION=$(bun run playwright --version | grep -oE '[0-9]+(\.[0-9]+)+')
            ;;
          deno)
            VERSION=$(deno run playwright --version | grep -oE '[0-9]+(\.[0-9]+)+')
            ;;
          *)
            echo "Unsupported package manager: ${{ inputs.package-manager }}"
            exit 1
            ;;
        esac
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Playwright version: $VERSION"

    - name: Set Playwright cache path
      id: playwright-cache-path
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          CACHE_PATH="$LOCALAPPDATA/ms-playwright"
        else
          CACHE_PATH="$HOME/.cache/ms-playwright"
        fi
        echo "path=$CACHE_PATH" >> $GITHUB_OUTPUT
        echo "Playwright cache path: $CACHE_PATH"

    - name: Cache Playwright browsers
      id: cache-playwright
      uses: actions/cache@v5
      with:
        path: ${{ steps.playwright-cache-path.outputs.path }}
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}-${{ inputs.browsers }}
        restore-keys: |
          ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}-

    - name: Install Playwright browsers
      if: steps.cache-playwright.outputs.cache-hit != 'true'
      shell: bash
      run: |
        case "${{ inputs.package-manager }}" in
          pnpm)
            pnpm exec playwright install --with-deps ${{ inputs.browsers }}
            ;;
          npm)
            npm exec playwright install --with-deps ${{ inputs.browsers }}
            ;;
          yarn)
            yarn exec playwright install --with-deps ${{ inputs.browsers }}
            ;;
          bun)
            bun run playwright install --with-deps ${{ inputs.browsers }}
            ;;
          deno)
            deno run playwright install --with-deps ${{ inputs.browsers }}
            ;;
          *)
            echo "Unsupported package manager: ${{ inputs.package-manager }}"
            exit 1
            ;;
        esac