name: rush-ts-build
on:
  workflow_call:
    secrets:
      codacy-token:
        required: true
jobs:
  typescript:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global core.eol LF
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v3
      - name: rush install
        run: node common/scripts/install-run-rush.js install --bypass-policy
      - name: rush build
        run: node common/scripts/install-run-rush.js build
      - name: rush test
        run: node common/scripts/install-run-rush.js test
