name: rush-ts-build
on:
  workflow_call:
    secrets:
      codacy-token:
        required: true
jobs:
  typescript:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global core.eol LF
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v3
      - name: install rush
        run: node common/scripts/install-run-rush.js install --bypass-policy
      - run: rush install
      - run: rush build
      - run: rush test