name: typescript-test
on:
  workflow_call:
jobs:
  typescript:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node-version: [12, 14, 16]
    steps:
      - run: git config --global core.eol LF
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - name: cache rush
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-rush-${{ hashFIles('rush.json') }}
          path: |
            common/temp/install-run
            ~/.rush
      - name: cache pnpm
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-rush-${{ hashFiles('common/config/rush/pnpm-lock.yaml')}}
          path: |
            common/temp/pnpm-store
      - name: rush install
        run: node common/scripts/install-run-rush.js install --bypass-policy
      - name: rush test
        run: node common/scripts/install-run-rush.js test
