name: typescript-test
on:
  workflow_call:
jobs:
  typescript:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node-version: [12, 14, 16]
    steps:
      - run: git config --global core.eol LF
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v3
      - name: install rush
        run: node common/scripts/install-run-rush.js install
      - run: rush install
      - run: rush test