name: typescript-build
on:
  workflow_call:
    secrets:
      codecov-token:
        required: true
      codacy-token:
        required: true
jobs:
  typescript:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global core.eol LF
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - name: setup yarn-cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: cache yarn global cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - run: yarn lint
      - run: yarn build
      - run: yarn size-limit
      - run: yarn dependency-check
      - run: yarn coverage --maxWorkers=2
      - name: codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.codecov-token }}
      - name: codacy
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.codacy-token }}
          coverage-reports: coverage/clover.xml
      - name: upload cjs folder
        uses: actions/upload-artifact@v3
        with:
          name: cjs
          path: cjs
      - name: upload esm folder
        uses: actions/upload-artifact@v3
        with:
          name: esm
          path: esm

