name: rush-ts-build
on:
  workflow_call:
    secrets:
      codacy-token:
        required: true
jobs:
  typescript:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'
    steps:
      - run: git config --global core.eol LF
      - run: git config --global core.autocrlf false
      - name: Start xvfb for vscode extension testing
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo ">>> Started xvfb"
      - uses: actions/checkout@v4
      - name: cache rush
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-rush-${{ hashFIles('rush.json') }}
          path: |
            common/temp/install-run
            ~/.rush
      - name: cache pnpm
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-rush-${{ hashFiles('common/config/rush/pnpm-lock.yaml')}}
          path: |
            common/temp/pnpm-store
      - name: rush install
        run: node common/scripts/install-run-rush.js install --bypass-policy
      - name: rush build
        run: node common/scripts/install-run-rush.js build
      - name: rush test
        run: node common/scripts/install-run-rush.js test -v
